include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
    strict-casts: true
  errors:
    unrelated_type_equality_checks: error
    missing_return: error
    body_might_complete_normally_nullable: error
    parameter_assignments: error
linter:
  rules:
    always_use_package_imports: true
    prefer_const_constructors: false
    always_declare_return_types: true
